default_stages: [commit]
repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.18.0
  hooks:
    - id: commitizen
      stages:
        - commit-msg

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_documented_variables
    - id: terraform_tfsec
    - id: terraform_checkov
    #- id: infracost_breakdown
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=./README.md
        - --hook-config=--add-to-exiting-file=true
        - --hook-config=--create-file-if-not-exist=true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
