# .pre-commit-config.yaml
default_stages: [commit]
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.18.0
      hooks:
          - id: commitizen
            stages:
                - commit-msg
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.75.0
      hooks:
          - id: terraform_fmt
          - id: terraform_validate
          - id: terraform_tflint

          - id: terraform_docs
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files