name: Release
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pre-Commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args:
            commitizen
            terraform_fmt --all-files
            terraform_validate
            terraform_docs_replace
            trailing-whitespace
            end-of-file-fixer
            check-yaml
            check-added-large-files

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git

          branches: |
            ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
